- name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: www
          remote: crmtour.com/www
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}